# Generated by Django 4.1.7 on 2024-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUs',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('slot', models.CharField(max_length=255)),
                ('chipset', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('gpu_model', models.CharField(max_length=255)),
                ('gpu_speed_oc', models.PositiveIntegerField()),
                ('gpu_speed_gaming', models.PositiveIntegerField()),
                ('memory_speed', models.PositiveIntegerField()),
                ('memory_size', models.PositiveIntegerField()),
                ('memory_type', models.CharField(max_length=255)),
                ('cuda_cores', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('max_resolution', models.CharField(max_length=255)),
                ('directx_support', models.CharField(max_length=255)),
                ('crossfire_sli_support', models.CharField(max_length=255)),
                ('dvi_port', models.PositiveIntegerField()),
                ('hdmi_port', models.PositiveIntegerField()),
                ('display_port', models.PositiveIntegerField()),
                ('option_port', models.CharField(max_length=255)),
                ('power_consumption', models.CharField(max_length=255)),
                ('power_supply_requirement', models.PositiveIntegerField()),
                ('power_connectors', models.CharField(max_length=255)),
                ('warranty_years', models.PositiveIntegerField()),
            ],
        ),
    ]
