# Generated by Django 4.1.7 on 2024-06-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_userprofile_delete_admininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_modified_at',
        ),
    ]
