# Generated by Django 4.1.7 on 2024-06-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_userprofile_last_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='graphics_card_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
