# Generated by Django 4.1.7 on 2024-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpus',
            name='GPU_id',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
