# Generated by Django 4.1.7 on 2024-06-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_store_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
    ]
