# Generated by Django 4.1.7 on 2024-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_gpus_gpu_id_store_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_num',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
