# Generated by Django 4.1.7 on 2024-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
