# Generated by Django 4.1.7 on 2024-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_store_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='graphics_card_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
