# Generated by Django 4.1.7 on 2024-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_store_graphics_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gpu_images/'),
        ),
    ]
