# Generated by Django 4.1.7 on 2024-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_gpus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
