# Generated by Django 4.1.7 on 2024-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_gpus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='gpus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gpu_images/'),
        ),
    ]
