# Generated by Django 4.1.7 on 2024-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_userprofile_profile_image_alter_gpus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/no_image.png', upload_to='profile_pictures/'),
        ),
    ]
